name: Build and Test Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ opened, reopened, edited ]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Copy AGREE Analysis Action
      uses: actions/checkout@v3
      with:
        repository: loonwerks/AGREE-CI-Action
        path: AGREE-CI-Action
    - name: AGREE Analysis
      uses: ./AGREE-CI-Action
      with:
        project-name: AGREE-Toy-Example
        component-to-analyze: Integer_Toy::top_level.Impl
        analysis-strategy: single

